apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260616-004615-g22e3740yex1-service
spec:
  selector:
    app: enterprise-system-20260616-004615-g22e3740yex1
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
